# minimal when using setup.cfg

[build-system]
requires = [
   "setuptools",
    "wheel",
    "robo-base",]
    
# Minimum requirements to build package in setuptools venv 
#requires = [
#    "setuptools",
#   "wheel",]
    



    "setuptools",
    "wheel",]
    
